version: "3.7"
services:
  bq:
    image: ghcr.io/goccy/bigquery-emulator:latest
    ports:
      - "9050:9050"
    volumes:
      - ./testdata:/testdata
    command: "bigquery-emulator --project=test --data-from-yaml=../testdata/data.yml"
  app:
    restart: always
    build: .
    tty: true
    volumes:
      - ./app:/app
